const app=document.querySelector('#app'), title=document.querySelector('#page-title'); let page='overview';
const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function api(path,options){const r=await fetch('/api/'+path,options);if(!r.ok)throw new Error(await r.text());return r.json()}
function badge(d){return `<span class="pill ${d}">${d}</span>`}
async function render(){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page)); if(page==='overview')return overview();if(page==='agents')return agents();if(page==='policies')return policies();if(page==='logs')return logs();return lab()}
async function overview(){title.textContent='Secure what AI does.';const d=await api('dashboard'), ev=await api('events'), ag=await api('agents');app.innerHTML=`<div class="stats">${[['Active Agents',d.active_agents],['Actions Today',d.actions_today],['Blocked',d.blocked],['Human Review',d.human_review],['High Risk',d.high_risk]].map(([x,y])=>`<div class="card"><div class="label">${x}</div><div class="metric">${y}</div></div>`).join('')}</div><div class="grid"><div class="panel"><h2>Recent security decisions</h2>${ev.length?ev.slice(0,5).map(e=>eventRow(e)).join(''):'<p class="muted">No actions yet. Run a Security Lab scenario.</p>'}</div><div class="panel"><h2>Runtime status</h2><p class="muted">${d.enforcement_notice}</p><pre>MODE: MVP SIMULATION\nHOST ENFORCEMENT: OFF\nLINUX RUNTIME: EXPERIMENTAL</pre></div></div>`}
function eventRow(e){return `<div class="row"><div><b>${esc(e.action)} → ${esc(e.target)}</b><small class="agent-name">${esc(e.reason)}</small></div>${badge(e.decision)}</div>`}
async function agents(){title.textContent='Active agents';const list=await api('agents');app.innerHTML=`<div class="panel"><h2>Agent inventory</h2>${list.map(a=>`<div class="row"><div class="agent-name">${esc(a.name)}<small>${esc(a.purpose)} · ${esc(a.model)} · ${esc(a.status)}</small></div><button class="link" onclick="showAgent('${a.id}')">View boundary →</button></div>`).join('')}</div>`}
async function showAgent(id){const [a,b]=await Promise.all([api('agents/'+id),api('agents/'+id+'/boundary')]);title.textContent=a.name;app.innerHTML=`<div class="grid"><div class="panel"><h2>Agent configuration</h2><div class="row"><span>Purpose</span><b>${esc(a.purpose)}</b></div><div class="row"><span>Task</span><b>${esc(a.task)}</b></div><div class="row"><span>Tools</span><b>${esc(a.tools.join(', '))}</b></div><div class="row"><span>Data</span><b>${esc(a.data.join(', '))}</b></div><div class="row"><span>Approval</span><b>${esc(a.approval_requirements)}</b></div></div><div class="panel"><h2>Compiled boundary</h2><pre>${esc(JSON.stringify(b,null,2))}</pre><p class="muted">Deterministic prototype; it has not applied an OS boundary.</p></div></div>`}
async function policies(){title.textContent='Policies';app.innerHTML=`<div class="panel"><h2>Demo policy rules</h2>${[['secrets-deny','Block private keys and host credentials'],['system-files-deny','Block /etc/shadow'],['data-scope-deny','Block production customer data'],['egress-deny','Block customer-data exfiltration'],['payment-approval','Review payments over $1,000'],['workspace-write','Allow edits under /workspace'],['default-review','Review any unmatched action']].map(x=>`<div class="row"><b>${x[0]}</b><span class="muted">${x[1]}</span></div>`).join('')}<p class="muted">These are application-level simulated rules, not a production policy enforcement system.</p></div>`}
async function logs(){title.textContent='Action & security log';const ev=await api('events');app.innerHTML=`<div class="panel"><h2>Audit events</h2>${ev.length?ev.map(e=>`<div class="row"><div><b>${esc(e.action)} → ${esc(e.target)}</b><small class="agent-name">${new Date(e.timestamp).toLocaleString()} · ${esc(e.rule)} · <button class="link" onclick="detail('${e.id}')">Why?</button></small></div>${badge(e.decision)}</div>`).join(''):'<p class="muted">No recorded actions.</p>'}</div>`}
async function detail(id){const e=await api('events/'+id);title.textContent='Security event detail';app.innerHTML=`<div class="grid"><div class="panel"><h2>${badge(e.decision)} ${esc(e.action)} → ${esc(e.target)}</h2><p>${esc(e.reason)}</p><div class="row"><span>Rule</span><b>${esc(e.rule)}</b></div><div class="row"><span>Time</span><b>${new Date(e.timestamp).toLocaleString()}</b></div></div><div class="panel"><h2>Enforcement status</h2><pre>${esc(e.enforcement)}</pre><p class="muted">This event was recorded by the demo API. No real tool call or host operation was stopped.</p></div></div>`}
async function lab(){title.textContent='Security Lab';const s=await api('scenarios');app.innerHTML=`<p class="muted">Safely exercise simulated attacks. No real files, payments, customer records, or network calls are touched.</p><div class="lab">${s.map(x=>`<article class="scenario"><span class="pill ${x.expected}">EXPECTED ${x.expected}</span><h3>${esc(x.title)}</h3><p class="muted">Runs an in-memory demo action against the policy engine.</p><button class="primary" onclick="runScenario('${x.id}')">Run scenario</button><div id="result-${x.id}"></div></article>`).join('')}</div>`}
async function runScenario(id){const s=(await api('scenarios')).find(x=>x.id===id);const r=await api('actions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...s,agent_id:'demo-agent'})});document.querySelector('#result-'+id).innerHTML=`<p>${badge(r.decision)} <span class="muted">${esc(r.reason)}</span></p>`}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelector('#new-agent').onclick=()=>document.querySelector('#agent-dialog').showModal();document.querySelector('#close-agent-dialog').onclick=()=>document.querySelector('#agent-dialog').close();document.querySelector('#agent-form').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),split=k=>(f.get(k)||'').split(',').map(x=>x.trim()).filter(Boolean);let a={name:f.get('name'),purpose:f.get('purpose'),model:f.get('model'),framework:f.get('framework'),task:f.get('task'),tools:split('tools'),data:split('data'),permissions:split('permissions'),limits:{note:f.get('limits')},approval_requirements:f.get('approval_requirements')};await api('agents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(a)});document.querySelector('#agent-dialog').close();page='agents';render()};render();
